### ISSUE TITLE
Fix for build error with boost::prior

### ISSUE THREAD

**Issue by arn13** [thomasp85/euclid#31]
According to [this issue](https://github.com/rst-tu-dortmund/teb_local_planner/issues/214) boost::prior has bee moved. This leads to an error when trying to build the package: 
```
error: ‘prior’ is not a member of ‘boost’; did you mean ‘boost::mpl::prior’?
  144 |        k.construct_segment_3_object()(*pts.begin(), *boost::prior(pts.end())));
      |                                      
```
The fix mentioned in the issue above works to resolve this error.

`#include <boost/next_prior.hpp>` has to be added into  Plane_3_Triangle_3_intersection.h

**Comment by dylanbeaudette** [comment]
Hi, just wanted to provide some updates on this issue based on a few hours of tinkering. Let me see if I can outline my notes here:

 * euclid links to [cgalh](https://github.com/dickoa/cgalh) which appears to be using some very old include files that reference the boost library
 * the boost library has since undergone internal reorganization such that `boost::prior` is no longer available using the include files from [cgalh](https://github.com/dickoa/cgalh)
 * the system CGAL include files (5.6-1build3 on my machine) correctly use `std::prev` instead of `boost::prior`
 * the [RcppCGAL package](https://github.com/ericdunipace/RcppCGAL) (version 6.1) correctly use `std::prev` instead of `boost::prior`
 * it is possible to [hack a fix or the cgalh include files](https://github.com/rst-tu-dortmund/teb_local_planner/issues/214) but this seems like a poor solution in general
 * it should be able to link to CGAL include files via RcppCGAL package, but I can't get that to work (see below)
 * removing cgalh from the LinkingTo directive in DESCRIPTION, and the package builds cleaning!


When adding RcppCGAL to the LinkingTo directive in DESCRIPTION results in:
```
g++ -std=gnu++14 -I"/usr/local/lib/R/include" -DNDEBUG -DCGAL_DO_NOT_USE_BOOST_MP -DCGAL_USE_GMPXX -DCGAL_NDEBUG  -I../inst/include/internal/ -I'/home/family/R/x86_64-pc-linux-gnu-library/4.4/cpp11/include' -I'/home/family/R/x86_64-pc-linux-gnu-library/4.4/RcppCGAL/include' -I'/home/family/R/x86_64-pc-linux-gnu-library/4.4/BH/include' -I/usr/local/include    -fpic  -g -O2   -c api.cpp -o api.o
In file included from /home/family/R/x86_64-pc-linux-gnu-library/4.4/RcppCGAL/include/CGAL/basic.h:21,
                 from /home/family/R/x86_64-pc-linux-gnu-library/4.4/RcppCGAL/include/CGAL/Cartesian/Cartesian_base.h:20,
                 from /home/family/R/x86_64-pc-linux-gnu-library/4.4/RcppCGAL/include/CGAL/Simple_cartesian.h:20,
                 from /home/family/R/x86_64-pc-linux-gnu-library/4.4/RcppCGAL/include/CGAL/Exact_predicates_exact_constructions_kernel.h:20,
                 from ../inst/include/internal/cgal_types.h:5,
                 from api.cpp:7:
/home/family/R/x86_64-pc-linux-gnu-library/4.4/RcppCGAL/include/CGAL/config.h:1:10: fatal error: Rcpp.h: No such file or directory
    1 | #include <Rcpp.h>
      |          ^~~~~~~~
```
I'm not sure if this is a simple configuration fix for RcppCGAL or not. That might be a more portable fix than insisting on system level include files being up to date.

Anyway, I think that the euclid family of packages are really interesting and I'd like to use them on my linux machines if possible.

**Comment by dylanbeaudette** [comment]
My notes and suggestions above also apply to polyclid and boundaries.

**Comment by dylanbeaudette** [comment]
Howdy. Wanted to report that euclid no longer compiles on Windows/RTools (R version 4.5.0, cgalh_5.5.1), with the following errors:
```
R/win-library/4.5/cgalh/include/CGAL/Circle_2.h: In member function 'typename CGAL::Circle_2<R_>::R::Boolean CGAL::Circle_2<R_>::is_degenerate() const':
R/win-library/4.5/cgalh/include/CGAL/Circle_2.h:163:21: error: 'is_zero' is not a member of 'CGAL'; did you mean 'Is_zero'?
  163 |     return CGAL_NTS is_zero(squared_radius());
      |                     ^~~~~~~
      |                     Is_zero
```
